name: SimpleSB
version: '1.0-SNAPSHOT'
main: me.idroom1.simplesb.SimpleSB
api-version: '1.20'
commands:
  sb:
    description: Toggles the scoreboard or reloads the config
    usage: /<command> [reload]
    permission: simplesb.admin
permissions:
  simplesb.admin:
    description: Allows the player to use SimpleSB commands
    default: op